### ISSUE TITLE
idees : pouvoir travailler à plusieurs

### ISSUE THREAD

**Issue by pepitpictures** [suancarloj/pepitpictures#10]
pouvoir traiter les photos et les envoyer sur les écrans, de différents ordi.. qui ne doivent pas recevoir trop trop de préparatif (hormis connexion à un éventuel réseau ou je sais pas tout quoi, avoir lightroom,..)

**Comment by suancarloj** [comment]
Sera possible dès qu'on aura mis en place le serveur web
