### ISSUE TITLE
bug :  actualisation de la page net des rasp

### ISSUE THREAD

**Issue by pepitpictures** [suancarloj/pepitpictures#11]
si ct passible dans nouveau systeme de pas devoir actualiser la page net des rasp ou chipoter nous meme avec la souris des client.. si les images pouvaient apparaitre direct (temps..) CA SERAIIIT BOOOOONNNN!!! lol

**Comment by suancarloj** [comment]
Sera résolu avec les nouveaux système

**Comment by pepitpictures** [comment]
:)
