### ISSUE TITLE
bug : connexion impassible : routeur

### ISSUE THREAD

**Issue by pepitpictures** [suancarloj/pepitpictures#6]
des fois j'utilise les wifi quand le câble bug et des fois j'utilise le câble quand le wifi bug... (en changeant les adresse des viewer)

pr le wifi il arrive pas a s'y connecté.. il fait des diagnostic en tout genre lol

**Comment by suancarloj** [comment]
Le plus fiable est de toujours utiliser le cable. On mettra un routeur beaucoup plus fiable avec le nouveau budget.
