### ISSUE TITLE
idees : récupérer les photos sur le site avec Réf.

### ISSUE THREAD

**Issue by pepitpictures** [suancarloj/pepitpictures#9]
lors de la vente des photos au "détail", à la place de les envoyer, que les gens aillent les récupérer sur mon site internet avec une référence que je leur donne à la vente (pas trop compliqué à écrire pour moi ni à retaper pour eux (genre début de leur nom par exemple ou je sais pas koi..)

est ce que ce système sera plus sur que par mail? 

problèmes rencontrés par mail: 
- les gens les reçoivent simplement pas.. ils m'envoient alors un mail et la je peu leur répondre avec leur photos
- ma boite à été pleine de mail avec toutes ces photos hors ça m'aurait arrangé de les garder comme ca je pouvais leur renvoyer en cas de soucis.. mais bon .. tampis
- les mails vont dans leur indésirable
- erreur de frappe lol

**Comment by suancarloj** [comment]
J'ai déjà une idée pour automatiser tout ça :p, ça devrait grandement te faciliter la vie !
